
--이하 INDIMOALOCAL 계정으로 실행
--만약에 있을 TABLE 삭제
DROP TABLE ADMIN;
DROP TABLE NOTICE_BOARD;
DROP TABLE EVENT_BOARD;
DROP TABLE NEWS_BOARD;
DROP TABLE FAQ_BOARD;
DROP TABLE GAME_IMAGE;
DROP TABLE ANSWER_BOARD;
DROP TABLE PLAYINFO;
DROP TABLE ORDER_GAME;
DROP TABLE GAME;
DROP TABLE REFUND;
DROP TABLE POINT;
DROP TABLE HEADING;
DROP TABLE MEMBER;
DROP TABLE GAME_DEV;
DROP TABLE GAME_INCART;
DROP TABLE CART;
DROP TABLE ORDER_DETAIL;
DROP TABLE GAME_DEV_BOARD;
DROP TABLE TIP_BOARD;
DROP TABLE REPORT_BLAME;
DROP TABLE FREE_BOARD_M;
DROP TABLE ASK_BOARD;
DROP TABLE REVIEW_BOARD;
DROP TABLE MEMBERSHIP;

--이하 테이블 및 컬럼생성

CREATE TABLE ADMIN(
    AD_ID VARCHAR(20) NOT NULL,
    AD_PWD VARCHAR(20) NOT NULL,
    AD_LOGINTIME TIMESTAMP NOT NULL, 
    
    CONSTRAINT ADMIN_PK PRIMARY KEY(AD_ID)
);

CREATE TABLE NOTICE_BOARD(
    NT_NO NUMBER(11) NOT NULL,
    AD_ID VARCHAR(20) NOT NULL,
    NT_CONTENT VARCHAR(255) NOT NULL,
    NT_DATETIME TIMESTAMP NOT NULL,
    
    CONSTRAINT NT_PK PRIMARY KEY(NT_NO),
    CONSTRAINT NT_FK FOREIGN KEY(AD_ID) 
        REFERENCES ADMIN(AD_ID)
);

CREATE TABLE EVENT_BOARD(
    EV_NO NUMBER(11) NOT NULL,
    AD_ID VARCHAR(20) NOT NULL,
    EV_CONTENT VARCHAR(255) NOT NULL,
    EV_DATETIME TIMESTAMP NOT NULL,
    
    CONSTRAINT EV_PK PRIMARY KEY(EV_NO),
    CONSTRAINT EV_FK FOREIGN KEY(AD_ID) 
        REFERENCES ADMIN(AD_ID)
);

CREATE TABLE NEWS_BOARD(
    NW_NO NUMBER(11) NOT NULL,
    AD_ID VARCHAR(20) NOT NULL,
    NW_TITLE VARCHAR(20) NOT NULL,
    NW_CONTENT VARCHAR(255) NOT NULL,
    NW_DATETIME TIMESTAMP NOT NULL,
    NW_VISIT NUMBER(10) NOT NULL,    
    NW_REPLY NUMBER(20) NOT NULL,
    
    CONSTRAINT NW_PK PRIMARY KEY(NW_NO),
    CONSTRAINT NW_FK FOREIGN KEY(AD_ID) 
        REFERENCES ADMIN(AD_ID)
);

CREATE TABLE FAQ_BOARD(
    FQ_NO NUMBER(11) NOT NULL,
    AD_ID VARCHAR(20) NOT NULL,
    FQ_TITLE VARCHAR(20) NOT NULL,
    FQ_CONTENT VARCHAR(255) NOT NULL,
    FQ_DATETIME TIMESTAMP NOT NULL,
    FQ_VISIT NUMBER(10) NOT NULL,    
    FQ_REPLY NUMBER(20) NOT NULL,
    
    CONSTRAINT FQ_PK PRIMARY KEY(FQ_NO),
    CONSTRAINT FQ_FK FOREIGN KEY(AD_ID) 
        REFERENCES ADMIN(AD_ID)
);

CREATE TABLE GAME_DEV(
    GD_GAMEDEVID VARCHAR(20) NOT NULL,
    GD_NAME VARCHAR(20) NOT NULL,
    GD_ADDRESS VARCHAR(255) NOT NULL,
    GD_PHONE VARCHAR(20) NOT NULL,
    GD_LEADERNAME VARCHAR(20) NOT NULL,    
    GD_LEADERMAIL VARCHAR(20) NOT NULL,
    GD_PROFILE VARCHAR(255) NOT NULL,
    
    CONSTRAINT GD_PK PRIMARY KEY(GD_GAMEDEVID)
    
);

CREATE TABLE GAME(
    GG_NO NUMBER(11) NOT NULL,
    GG_TITLE VARCHAR(20) NOT NULL,
    GG_PRICE NUMBER(11) NOT NULL,
    GG_SYSTEM_REQUIREMENTS VARCHAR(255) NOT NULL,
    GG_GENRE VARCHAR(255) NOT NULL,
    GG_DEVELOPER VARCHAR(30) NOT NULL, 
    GG_RELEASE_DATE TIMESTAMP NOT NULL,
    GG_PUBLISHER VARCHAR(20) NOT NULL,
    GG_LANGUAGES VARCHAR(30) NOT NULL,
    GG_INFORMATION VARCHAR(2000) NOT NULL,
    
    CONSTRAINT GG_PK PRIMARY KEY(GG_NO),
);

CREATE TABLE GAME_IMAGE(
    GI_NO NUMBER(11) NOT NULL,
    GI_NO NUMBER(11) NOT NULL,
    ORIGIN_FILE_ADDRESS VARCHAR(300) NOT NULL,
    
    CONSTRAINT GI_PK PRIMARY KEY(GI_NO),
);

CREATE TABLE MEMBER(
    MM_ID VARCHAR(20) NOT NULL,
    MM_PWD VARCHAR(20) NOT NULL,
    MM_EMAIL VARCHAR(20) NOT NULL,
    MM_PHN VARCHAR(20) NOT NULL,
    MM_COM VARCHAR(20) NOT NULL,
    MM_ENROLLDATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
    MM_PROFILE VARCHAR(255) NOT NULL,
    MM_NICKNAME VARCHAR(255) NOT NULL,
    MM_MEMBERSHIP VARCHAR(20) NOT NULL,
    
    CONSTRAINT MM_PK PRIMARY KEY(MM_ID)
);

CREATE TABLE ORDER_GAME(
    OR_GG_NO NUMBER(11) NOT NULL,
    MM_ID VARCHAR(20) NOT NULL,
    GG_NO NUMBER(11) NOT NULL,
    GD_GAMEDEVID VARCHAR(20) NOT NULL,
    OR_COUNT NUMBER(11) NOT NULL,
    
    CONSTRAINT OR_PK PRIMARY KEY(OR_GG_NO),
    CONSTRAINT OR_FK1 FOREIGN KEY(MM_ID) 
        REFERENCES MEMBER(MM_ID) ON DELETE CASCADE,
    CONSTRAINT OR_FK2 FOREIGN KEY(GG_NO) 
        REFERENCES GAME(GG_NO),
    CONSTRAINT OR_FK3 FOREIGN KEY(GD_GAMEDEVID) 
        REFERENCES GAME_DEV(GD_GAMEDEVID)
);

CREATE TABLE PLAYINFO(
    OR_GG_NO NUMBER(11) NOT NULL,
    MM_ID VARCHAR(20) NOT NULL,
    GG_NO NUMBER(11) NOT NULL,
    GD_GAMEDEVID VARCHAR(20) NOT NULL,
    PL_TIME NUMBER(11) NOT NULL,
    PL_PC VARCHAR(255) NOT NULL,
    
    CONSTRAINT PL_FK1 FOREIGN KEY(OR_GG_NO)
        REFERENCES ORDER_GAME(OR_GG_NO),
    CONSTRAINT PL_FK2 FOREIGN KEY(MM_ID) 
        REFERENCES MEMBER(MM_ID) ON DELETE CASCADE,
    CONSTRAINT PL_FK3 FOREIGN KEY(GG_NO) 
        REFERENCES GAME(GG_NO),
    CONSTRAINT PL_FK4 FOREIGN KEY(GD_GAMEDEVID) 
        REFERENCES GAME_DEV(GD_GAMEDEVID)
);

CREATE TABLE REFUND(
    RU_NO NUMBER(11) NOT NULL,
    OR_GG_NO NUMBER(11) NOT NULL,
    GG_NO NUMBER(11) NOT NULL,
    GD_GAMEDEVID VARCHAR(20) NOT NULL,
    MM_ID VARCHAR(20) NOT NULL,
    RU_CONTENT VARCHAR(255) NOT NULL,
    RU_CLAIMER VARCHAR(20) NOT NULL,
    RU_DATETIME TIMESTAMP DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT RU_PK PRIMARY KEY(RU_NO),
    CONSTRAINT RU_FK1 FOREIGN KEY(OR_GG_NO)
        REFERENCES ORDER_GAME(OR_GG_NO),
    CONSTRAINT RU_FK2 FOREIGN KEY(GG_NO) 
        REFERENCES GAME(GG_NO),
    CONSTRAINT RU_FK3 FOREIGN KEY(GD_GAMEDEVID) 
        REFERENCES GAME_DEV(GD_GAMEDEVID),
    CONSTRAINT RU_FK4 FOREIGN KEY(MM_ID)
        REFERENCES MEMBER(MM_ID) ON DELETE CASCADE
);

CREATE TABLE POINT(
    MM_ID VARCHAR(20) NOT NULL,
    PT_REASON VARCHAR(20) NOT NULL,
    PT_SIZE NUMBER(11) NOT NULL,
    PT_DATETIME TIMESTAMP DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT PT_FK FOREIGN KEY(MM_ID) 
        REFERENCES MEMBER(MM_ID) ON DELETE CASCADE
);

CREATE TABLE ORDER_DETAIL(
    OD_NO NUMBER(11) NOT NULL,
    OR_GG_NO NUMBER(11) NOT NULL,
    GG_NO NUMBER(11) NOT NULL,
    GD_GAMEDEVID VARCHAR(20) NOT NULL,
    MM_ID VARCHAR(20) NOT NULL,
    OD_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
    OD_PRICE NUMBER(11) NOT NULL,
    OD_COUNT NUMBER(11) NOT NULL,
    OD_TOTALPRICE NUMBER(11) NOT NULL,
    
    
    CONSTRAINT OD_PK PRIMARY KEY(OD_NO),
    CONSTRAINT OD_FK1 FOREIGN KEY(OR_GG_NO)
        REFERENCES ORDER_GAME(OR_GG_NO),
    CONSTRAINT OD_FK2 FOREIGN KEY(GG_NO) 
        REFERENCES GAME(GG_NO),
    CONSTRAINT OD_FK3 FOREIGN KEY(GD_GAMEDEVID) 
        REFERENCES GAME_DEV(GD_GAMEDEVID),
    CONSTRAINT OD_FK4 FOREIGN KEY(MM_ID)
        REFERENCES MEMBER(MM_ID) ON DELETE CASCADE
);

CREATE TABLE CART(
    CT_NO NUMBER(11) NOT NULL,
    MM_ID VARCHAR(20) NOT NULL,
    CT_CONTENT VARCHAR(255) NOT NULL,
    CT_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT CT_PK PRIMARY KEY(CT_NO),
    CONSTRAINT MM_ID FOREIGN KEY(MM_ID)
        REFERENCES MEMBER(MM_ID) ON DELETE CASCADE
);

CREATE TABLE GAME_INCART(
    GG_NO NUMBER(11) NOT NULL,
    CT_NO NUMBER(11) NOT NULL,
    MM_ID VARCHAR(20) NOT NULL,
    
    CONSTRAINT IC_FK1 FOREIGN KEY (GG_NO)
        REFERENCES GAME(GG_NO),
    CONSTRAINT IC_FK2 FOREIGN KEY (CT_NO)
        REFERENCES CART(CT_NO),
    CONSTRAINT IC_FK3 FOREIGN KEY (MM_ID)
        REFERENCES MEMBER(MM_ID) ON DELETE CASCADE
);

CREATE TABLE FREE_BOARD_M( 
    FB_NO NUMBER(11) NOT NULL,
    MM_ID VARCHAR(20) NOT NULL,
    FB_TITLE VARCHAR(20) NOT NULL,
    FB_CONTENT VARCHAR(255) NOT NULL,
    FB_DATETIME TIMESTAMP DEFAULT SYSDATE NOT NULL,
    FB_VISIT NUMBER(10) NOT NULL,
    FB_REPLY NUMBER(20) NOT NULL,
    FB_REPORT VARCHAR(20) NOT NULL,
    
    CONSTRAINT FB_PK PRIMARY KEY(FB_NO),
    CONSTRAINT FB_FK FOREIGN KEY(MM_ID) 
        REFERENCES MEMBER(MM_ID) ON DELETE CASCADE
);

CREATE TABLE ASK_BOARD(
    ASK_NO NUMBER(11) NOT NULL,
    MM_ID VARCHAR(20) NOT NULL,
    ASK_TITLE VARCHAR(20) NOT NULL,
    ASK_CONTENT VARCHAR(255) NOT NULL,
    ASK_DATETIME TIMESTAMP DEFAULT SYSDATE NOT NULL,
    ASK_VISIT NUMBER(10) NOT NULL,
    ASK_REPLY NUMBER(20) NOT NULL,
    ASK_REPORT VARCHAR(20) NOT NULL,
    
    CONSTRAINT ASK_PK PRIMARY KEY(ASK_NO),
    CONSTRAINT ASK_FK FOREIGN KEY(MM_ID)
        REFERENCES MEMBER(MM_ID) ON DELETE CASCADE
);

CREATE TABLE REVIEW_BOARD(
    RV_NO NUMBER(11) NOT NULL,
    MM_ID VARCHAR(20) NOT NULL,
    RV_TITLE VARCHAR(20) NOT NULL,
    RV_CONTENT VARCHAR(255) NOT NULL,
    RV_DATETIME TIMESTAMP DEFAULT SYSDATE NOT NULL,
    RV_VISIT NUMBER(10) NOT NULL,
    RV_REPLY NUMBER(20) NOT NULL,
    RV_REPORT VARCHAR(20) NOT NULL,
    
    CONSTRAINT RV_PK PRIMARY KEY (RV_NO),
    CONSTRAINT RV_FK FOREIGN KEY (MM_ID) 
        REFERENCES MEMBER(MM_ID) ON DELETE CASCADE
);

CREATE TABLE TIP_BOARD(
    TIP_NO NUMBER(11) NOT NULL,
    GD_GAMEDEVID VARCHAR(20) NOT NULL,
    TIP_TITLE VARCHAR(20) NOT NULL,
    TIP_CONTENT VARCHAR(255) NOT NULL,
    TIP_DATETIME TIMESTAMP DEFAULT SYSDATE NOT NULL,
    TIP_VISIT NUMBER(10) NOT NULL,
    TIP_REPLY NUMBER(20) NOT NULL,
    TIP_REPORT VARCHAR(20) NOT NULL,
    
    CONSTRAINT TIP_PK PRIMARY KEY (TIP_NO),
    CONSTRAINT TIP_FK FOREIGN KEY (GD_GAMEDEVID) 
        REFERENCES GAME_DEV(GD_GAMEDEVID)
);

CREATE TABLE HEADING(
    HE_HEADING VARCHAR(20) NOT NULL,
    CONSTRAINT HB_PK PRIMARY KEY (HE_HEADING)
);

CREATE TABLE GAME_DEV_BOARD(
    GB_NO NUMBER(11) NOT NULL,
    GD_GAMEDEVID VARCHAR(20) NOT NULL,
    HE_HEADING VARCHAR(20) NOT NULL,
    GB_TITLE VARCHAR(20) NOT NULL,
    GB_CONTENT VARCHAR(255) NOT NULL,
    GB_DATETIME TIMESTAMP DEFAULT SYSDATE NOT NULL,
    GB_VISIT NUMBER(10) NOT NULL,
    GB_REPLY NUMBER(20) NOT NULL,
    GB_REPORT VARCHAR(20) NOT NULL,
    
    CONSTRAINT GB_PK PRIMARY KEY (GB_NO),
    CONSTRAINT GB_FK1 FOREIGN KEY (GD_GAMEDEVID) 
        REFERENCES GAME_DEV(GD_GAMEDEVID),
    CONSTRAINT GB_FK2 FOREIGN KEY (HE_HEADING) 
        REFERENCES HEADING(HE_HEADING)
);

CREATE TABLE ANSWER_BOARD(
    AW_NO NUMBER(11) NOT NULL,
    AW_TITLE VARCHAR(20) NOT NULL,
    AW_CONTENT VARCHAR(255) NOT NULL,
    AW_DATETIME TIMESTAMP DEFAULT SYSDATE NOT NULL,
    AW_VISIT NUMBER(10) NOT NULL,
    AW_REPLY NUMBER(20) NOT NULL,
    AW_REPORT VARCHAR(20) NOT NULL,
    
    CONSTRAINT AW_PK PRIMARY KEY (AW_NO)
    
);

CREATE TABLE REPORT_BLAME(
    RT_ID VARCHAR(20) NOT NULL,
    TIP_NO NUMBER(11) ,
    ASK_NO NUMBER(11) ,
    RV_NO NUMBER(11) ,
    AW_NO NUMBER(11) ,
    GB_NO NUMBER(11) ,
    FB_NO NUMBER(11) ,
    RT_DATETIME TIMESTAMP DEFAULT SYSDATE NOT NULL,
    RT_DELETE VARCHAR(20) NOT NULL,
    
    CONSTRAINT RT_PK PRIMARY KEY (RT_ID),
    CONSTRAINT RT_FK1 FOREIGN KEY (TIP_NO) 
        REFERENCES TIP_BOARD(TIP_NO),
    CONSTRAINT RT_FK2 FOREIGN KEY (ASK_NO) 
        REFERENCES ASK_BOARD(ASK_NO),
    CONSTRAINT RT_FK3 FOREIGN KEY (RV_NO) 
        REFERENCES REVIEW_BOARD(RV_NO),
    CONSTRAINT RT_FK4 FOREIGN KEY (AW_NO) 
        REFERENCES ANSWER_BOARD(AW_NO),
    CONSTRAINT RT_FK5 FOREIGN KEY (GB_NO) 
        REFERENCES GAME_DEV_BOARD(GB_NO),
    CONSTRAINT RT_FK6 FOREIGN KEY (FB_NO) 
        REFERENCES FREE_BOARD_M(FB_NO)
);

CREATE TABLE MEMBERSHIP(
    MS_NO NUMBER(11) NOT NULL,
    MS_GAMEDEVID VARCHAR(20) NOT NULL,
    MS_TITLE VARCHAR(20) NOT NULL,
    MS_CONTENT VARCHAR(255) NOT NULL,
    MS_COST NUMBER(11) NOT NULL
    
);

CREATE SEQUENCE SEQ_GAME_GG_NO
INCREMENT BY 1
START WITH 00000000000
MAXVALUE 99999999999
NOCYCLE;
